# netlify.toml
[build]
  publish = "." # Changed from "build" to "."
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
