# netlify.toml
[build]
  publish = "build" # Or whatever your build output directory is (e.g., ".")
  functions = "netlify/functions" # This tells Netlify where your functions are located

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
